### ISSUE TITLE
Problem installing 10.3 on my MacBook M1

### ISSUE THREAD

**Issue by castal** [3-manifolds/Sage_macOS#66]
I have just today downloaded the most recent SageMath-10.3_arm64.dmg and installed in on my M1 mac. When I run the application and try to open a Jupyter session, nothing seems to happen at all. So I tried just running a terminal session.  The terminal output error message is appended below. However, 10.2 seems to work just fine, both in the terminal and with Jupyter. I hope I'm not just missing something obvious. Is it my python version?

Here is the terminal error output for 10.3:

┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 10.3, Release Date: 2024-03-19                    │
│ Using Python 3.11.1. Type "help()" for help.                       │
└────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "/private/var/tmp/sage-10.3-current/local/var/lib/sage/venv-python3.11.1/bin/sage-ipython", line 12, in <module>
    from sage.repl.interpreter import SageTerminalApp
  File "/private/var/tmp/sage-10.3-current/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/sage/repl/interpreter.py", line 145, in <module>
    from sage.repl.prompts import InterfacePrompts
  File "/private/var/tmp/sage-10.3-current/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/sage/repl/prompts.py", line 16, in <module>
    from IPython.terminal.prompts import Prompts
  File "/private/var/tmp/sage-10.3-current/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/IPython/__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "/private/var/tmp/sage-10.3-current/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/IPython/terminal/embed.py", line 15, in <module>
    from IPython.core.interactiveshell import DummyMod, InteractiveShell
  File "/private/var/tmp/sage-10.3-current/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 326, in <module>
    class InteractiveShell(SingletonConfigurable):
  File "/private/var/tmp/sage-10.3-current/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 331, in InteractiveShell
    ast_transformers: List[ast.NodeTransformer] = List(
                      ~~~~^^^^^^^^^^^^^^^^^^^^^
TypeError: type 'List' is not subscriptable

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by culler** [comment]
Thanks for reporting this.

I think you are having the exact same problem as was reported in #65.  (How could I forget that error message: 
"TypeError: type 'List' is not subscriptable"?)

I think you probably also have an old version of IPython that you installed in your .sage directory with the %pip command long ago.  Please retry running the app after moving your .sage directory out of the way by  running:
`mv ~/.sage ~/DOTsage`
in your Terminal. Please report if that fixes this.

Most likely you will just want to delete your current .sage directory and re-install whatever PyPI packages you actually need.  But you could also decide to move DOTsage back to .sage and try to repair it.

**Comment by castal** [comment]
That seems to have worked! My jupyter notebook looks a bit different, but
that's fine. I guess maybe it was just time to do some spring cleaning.
Anyway, thanks for your help!

**Comment by culler** [comment]
Great! I will close this ticket, then.
